### ISSUE TITLE
Galera Cluster Metrics

### ISSUE THREAD

**Issue by allanharris** [newrelic/nri-mysql#113]
### Description
[Galera](https://galeracluster.com/) is a popular multi-master solution for MySQL and MariaDB.
Galera cluster-specific metrics are available with this query:
`SHOW GLOBAL STATUS LIKE 'wsrep_%';`

Example output:
```
# Variable_name, Value
wsrep_protocol_version, 10
wsrep_last_committed, 36
wsrep_replicated, 0
wsrep_replicated_bytes, 0
wsrep_repl_keys, 0
wsrep_repl_keys_bytes, 0
wsrep_repl_data_bytes, 0
wsrep_repl_other_bytes, 0
wsrep_received, 6
wsrep_received_bytes, 1896

```

### Acceptance Criteria
wsrep_* metrics appear in NewRelic

### Estimates
S = 1-3 days

**Comment by davidgit** [comment]
Hi,

We consolidated multiple channels that were used to file Feature Requests (FRs). In the spirit of improving the visibility of FRs, we believe it's best for them to be submitted through the [New Relic Issue Tracker](https://issues.newrelic.com). This single tool will enable better aggregation of FRs and improve our ability to synthesize requests and provide better value to our users. You can see and vote for other FRs submitted by all users.

Please provide a link to this GitHub issue when submitting your feature request.

Thanks!
