### ISSUE TITLE
Missing some status variables

### ISSUE THREAD

**Issue by malusdei** [newrelic/nri-mysql#49]
Most of the variables from Mysql's SHOW STATUS are available in NRQL's MySQLsamples, but not the more recent ones, like the wsrep_* variables for Galera Cluster.  Could we get an update for the MySQLsamples available watch items?

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution for more than a year. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

**Comment by allanharris** [comment]
Hello, can you add this feature please?
