### ISSUE TITLE
Add custom query functionality

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-mysql#54]
## Feature Description
Add a custom metric query functionality as [nri-mssql](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration) has to allow additional columns collected with the query are added to the metric set as attributes.

**Comment by gsanchezgavier** [comment]
A PR #48  has been submitted but not completely finished for this.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
