### ISSUE TITLE
commands out of sync. Did you run multiple statements at once?

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-mysql#76]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When running queries, the resulting `Rows` object is scanned for data. Some error or skipping conditions might cause this process to be interrupted, and therefore the object not to be fully consumed. This might produce an error on a subsequent query.

## Expected Behavior

`Rows` object should be `Close()`d after the query is done to be scanned. Since the `Close()` option is idempotent, this can be easily done in a `defer` statement.

## Context

I believe this to be the root cause of the following error, reported by a customer:
```
"stderr": ["[FATAL] can't continue: commands out of sync. Did you run multiple statements at once?","panic: commands out of sync. Did you run multiple statements at once?","goroutine 1 [running]:","github.com/newrelic/nri-mysql/vendor/github.com/newrelic/infra-integrations-sdk/log.Fatal(0x783b00, 0xc420064600)","t/go/src/github.com/newrelic/nri-mysql/vendor/github.com/newrelic/infra-integrations-sdk/log/log.go:107 +0xd5","main.fatalIfErr(0x783b00, 0xc420064600)","t/go/src/github.com/newrelic/nri-mysql/src/mysql.go:152 +0x44","main.main()","t/go/src/github.com/newrelic/nri-mysql/src/mysql.go:115 +0x27f"]
```
Based on the info from the [docs](https://golang.org/pkg/database/sql/#Rows.Close) and [this question](https://stackoverflow.com/questions/614671/commands-out-of-sync-you-cant-run-this-command-now)

**Comment by paologallinaharbur** [comment]
After the fix the issue is still affecting the user, therefore I am reopening the issue.

**Comment by paologallinaharbur** [comment]
```go
// Read packet to buffer 'data'
func (mc *mysqlConn) readPacket() ([]byte, error) {
	var prevData []byte
	for {
		// read packet header
		data, err := mc.buf.readNext(4)
		if err != nil {
			if cerr := mc.canceled.Value(); cerr != nil {
				return nil, cerr
			}
			errLog.Print(err)
			mc.Close()
			return nil, ErrInvalidConn
		}

		// packet length [24 bit]
		pktLen := int(uint32(data[0]) | uint32(data[1])<<8 | uint32(data[2])<<16)

		// check packet sync [8 bit]
		if data[3] != mc.sequence {
			if data[3] > mc.sequence {
				return nil, "commands out of sync. Did you run multiple statements at once?"   <---- here is generated the error, inside the library
			}
			return nil, ErrPktSync
		}
		mc.sequence++
```

**Comment by roobre** [comment]
Customer reported the issue was solved by updating to the latest version. Closing since we cannot reproduce this anymore.

**Comment by alesak** [comment]
Hi,
we are having same issue with agent version 1.20.0:

`level=error msg="Integration command failed" error="exit status 2" instance=???? integration=com.newrelic.mysql prefix=config/mysql stderr="[FATAL] can't continue: commands out of sync. Did you run multiple statements at once?\npanic: commands out of sync. Did you run multiple statements at once?\n\ngoroutine 1 [running]:\ngithub.com/newrelic/nri-mysql/vendor/github.com/newrelic/infra-integrations-sdk/log.Fatal(0x781b00, 0xc420010620)\n\t/data/jenkins/infra-integrations-nri-mysql-release-linux-package-2/go/src/github.com/newrelic/nri-mysql/vendor/github.com/newrelic/infra-integrations-sdk/log/log.go:107 +0xd5\nmain.fatalIfErr(0x781b00, 0xc420010620)\n\t/data/jenkins/infra-integrations-nri-mysql-release-linux-package-2/go/src/github.com/newrelic/nri-mysql/src/mysql.go:133 +0x44\nmain.main()\n\t/data/jenkins/infra-integrations-nri-mysql-release-linux-package-2/go/src/github.com/newrelic/nri-mysql/src/mysql.go:96 +0x26d\n" working-dir=/var/db/newrelic-infra/newrelic-integrations`

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
