### ISSUE TITLE
allow supporting TLS/SSL

### ISSUE THREAD

**Issue by tjstansell** [newrelic/nri-mysql#87]
## Is your feature request related to a problem? Please describe.
We'd like to force SSL/TLS on all database connections.  I cannot see a way to enable this inside `nri-mysql`.  Similarly, for monitoring RDS nodes, we'd need the ability to update the CA used with a copy of `https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem`.

## Priority
Must Have

**Comment by mangulonr** [comment]
Issue already mentioned in [#88](https://github.com/newrelic/nri-mysql/pull/88)
